### PR TITLE
Proposed update to 1.12.2 plus several fixes with generation.

### PR DESCRIPTION
**Pull request by Xaphiosis**
I'd like to tune more things eventually, but want to see if you're at all interested in the basic update first.

### CODE REVIEW

**Comment by primetoxinz** [comment]
Looks good

**Comment by primetoxinz** [comment]
Thanks a lot for the PR, works great. Let me know when you tune th generation to a point that you're happy with and I will make a release

**Comment by Xaphiosis** [comment]
Awesome, glad you liked it!

I mainly wanted to revive the option to keep it in oceans, and maybe add a config to tune frequency of reef occurrence. How about you? Do you have any ideas on what you'd like improved that should make it into the next release?

**Comment by primetoxinz** [comment]
If you saw the configs I added after your PR I added a biome and dimension list which defaults to ocean/deep ocean only in the overworld

**Comment by primetoxinz** [comment]
Not sure if you would know how to make the noise make circular patches rather than continuous reefs or not but I would certainly like it to be like that.

**Comment by Xaphiosis** [comment]
I tested out your updated version. Looks good, and the sparsity tweaks are a good addition. I would suggest adding "beach" to the default supported biomes list.

Also, I think this is good enough for a 1.12.2 release, I don't see any quick improvements unless as you said, someone figures out a better generator pattern altogether.

An aside, my personal experience of coral reefs is that they tend to like slopes and shallower water. It still feels to me there is too much reef generated in the ocean, but changing the noise threshold will result in "rivers" of reef instead of the more isolated patches you'd like. Then again, in this game there's nothing else exciting in the ocean so I can live with it for now.

Thanks for being so quick to respond and making this a very pleasant exchange!

**Pull request merged**
